display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
quarkus:
  log:
    console:
      json:
        pretty-print: true
        date-format: "YYYY-MM-dd HH:mm:ss"
        exception-output-type: "detailed-and-formatted"
  mongodb:
    connection-string: mongodb://localhost:27017/maindb?uuidRepresentation=STANDARD
    database: maindb