application:
  entity-locker:
    enabled: true
    entity-restore-timeout: 10000
    entity-lock-timeout: 8000
    entity-process-timeout: 6000

display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
quarkus:
  http:
    port: 0
  log:
    console:
      json:
        pretty-print: true
        date-format: "YYYY-MM-dd HH:mm:ss"
        exception-output-type: "detailed-and-formatted"
  mongodb:
    connection-string: mongodb://localhost:27017/maindb?uuidRepresentation=STANDARD
    database: maindb
  redis:
    hosts: redis://localhost:6379