apiVersion: "serving.knative.dev/v1"
kind: "Service"
metadata:
  name: "quarkus-proto1"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: "docker.io/alissonvisa/code-with-quarkus:1.0.0-SNAPSHOT"